version: "3.9"

services:
  accent-analyzer:
    build: .
    ports:
      - "8000:8000"
    environment:
      GOOGLE_API_KEY: "your_key"
      HUGGINGFACE_TOKEN: "your_key"
      LANGSMITH_API_KEY: "your_key"
    restart: unless-stopped
