version: "3.9"

services:
  accent-analyzer:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}  # Pass your Google API key via .env or environment
    restart: unless-stopped
